#!/bin/bash
#PBS -N gnn_training
#PBS -l select=1:ncpus=16:ngpus=1:mem=110gb
#PBS -l walltime=01:00:00
#PBS -P personal-e1538240
#PBS -j oe

module purge
module load miniforge3

source activate myenv

nvidia-smi
python -c "import torch; print(torch.__version__, torch.cuda.is_available())"

cd $PBS_O_WORKDIR
python gnns/train_gat_single.py \
  --pt output/pyg_radius2_debruijn_dedup.pt \
  --imbalance class_weight \
  --epochs 200 \
  --batch_size 64 \
  --lr 1e-3

echo "Job completed at: $(date)"