#!/bin/bash
#PBS -N train_dependency_gnn
#PBS -l select=1:ncpus=16:ngpus=1:mem=110gb
#PBS -l walltime=01:00:00
#PBS -P personal-e1538240
#PBS -j oe

module purge
module load miniforge3

source activate myenv

nvidia-smi
python -c "import torch; print(torch.__version__, torch.cuda.is_available())"

cd $PBS_O_WORKDIR
python gnns/train_dependency_gnn.py --root output/pyg_radius2_dependency_std

echo "Job completed at: $(date)"