#!/bin/bash
#PBS -N train_6views_gnn
#PBS -l select=1:ncpus=16:ngpus=1:mem=110gb
#PBS -l walltime=01:00:00
#PBS -P personal-e1538240
#PBS -j oe

module purge
module load miniforge3

source activate myenv

nvidia-smi
python -c "import torch; print(torch.__version__, torch.cuda.is_available())"

cd $PBS_O_WORKDIR
python gnns/train_6views_gnn.py \
  --view-roots output/pyg_radius2_debruijn_std output/pyg_radius2_symbol01_std output/pyg_radius2_dependency_std \
  --view-names dbg sym dep \
  --hidden 96 \
  --class-weight-power 0.4


echo "Job completed at: $(date)"